### ISSUE TITLE
Flow Launcher is giving me these error popups

### ISSUE THREAD

**Issue by ChillFire22** [jjw24/Wox.Plugin.GoogleSearch#7] opened 2022-11-02 19:49 UTC
Logs:
> [2022-11-02.txt](https://github.com/jjw24/Wox.Plugin.GoogleSearch/files/9923695/2022-11-02.txt)
> [2022-11-01.txt](https://github.com/jjw24/Wox.Plugin.GoogleSearch/files/9923665/2022-11-01.txt)
> 

Hello, Flow Launcher has been great so far but every so often it gives me these error/ crash popups.
The programs still function properly but they are just annoying so I'm following their instructions and posting this here alongside the log files.

```
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 11/02/2022 21:48:03
Exception:
Google Search Plus Exception: 
Websites: https://github.com/jjw24/Wox.Plugin.GoogleSearch
Author: mikemorain
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: One or more errors occurred. (A task was canceled.)
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Wox.Plugin.GoogleSearch.GoogleSearch.Search(String query, Int32 limit) in D:\a\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\GoogleSearch.cs:line 30
   at Wox.Plugin.GoogleSearch.Main.Query(Query query) in D:\a\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\Main.cs:line 23
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Wox.Plugin.GoogleSearch.GoogleSearch.Search(String query, Int32 limit) in D:\a\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\GoogleSearch.cs:line 30
   at Wox.Plugin.GoogleSearch.Main.Query(Query query) in D:\a\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\Main.cs:line 23
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 626
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 627
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by jjw24** [comment] 2022-11-02 21:55
Hey how's it going, I will take a look. Would mind taking note of how or when it happens so I can reproduce it consistently please. So far I haven't been able to reproduce the error.

**Comment by TwelveNight** [comment] 2023-06-29 13:12
the same problem

**Comment by jjw24** [comment] 2023-07-02 07:48
Does it happen consistently for you?

**Comment by TwelveNight** [comment] 2023-07-02 10:13
> Does it happen consistently for you?

Yes

**Comment by jjw24** [comment] 2023-07-02 11:47
Could you please upload the log after the error pops up.

**Comment by TwelveNight** [comment] 2023-07-02 14:31
> Could you please upload the log after the error pops up.

Please open new issue in: https://github.com/jjw24/Wox.Plugin.GoogleSearch/issues
1. upload log file: C:\Users\lenovo\AppData\Roaming\FlowLauncher\Logs\1.15.0\2023-07-02.txt
2. copy below exception message

Flow Launcher version: 1.15.0
OS Version: 22000.2057
IntPtr Length: 8
x64: True

Python Path: D:\IDE\python3.10.10\pythonw.exe
Node Path: D:\Study_Software\nodejs\node.exe
Date: 07/02/2023 22:30:11
Exception:
Google Search Plus Exception:
Websites: https://github.com/jjw24/Wox.Plugin.GoogleSearch
Author: mike morain
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: One or more errors occurred. (A connection attempt failed because the connected party did not properly reply after a period of time or the connected host did not respond. (www.google.com:443))
  ---> System.AggregateException: One or more errors occurred. (A connection attempt failed because the connected party did not properly reply after a period of time or the connected host did not respond. (www.google.com:443))
  ---> System.Net.Http.HttpRequestException: The connection attempt failed because the connected party did not properly reply after a period of time or the connected host did not respond. (www.google.com:443)
  ---> System.Net.Sockets.SocketException (10060): The connection attempt failed because the connected party did not properly reply after a period of time or the connected host did not respond.
    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken origin alCancellationToken)
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
    at Wox.Plugin.GoogleSearch.GoogleSearch.Search(String query, Int32 limit) in D:\a\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\GoogleSearch.cs:line 30
    at Wox.Plugin.GoogleSearch.Main.Query(Query query) in D:\a\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\Main.cs:line 23
    at System.Threading.Tasks.Task`1.InnerInvoke()
    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
    at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
    at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
    --- End of inner exception stack trace ---
    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.

**Comment by tristansly** [comment] 2023-07-05 11:18
Please open new issue in: https://github.com/jjw24/Wox.Plugin.GoogleSearch/issues
1. upload log file: C:\Users\ech0-V\AppData\Roaming\FlowLauncher\Logs\1.15.0\2023-07-05.txt
2. copy below exception message

Flow Launcher version: 1.15.0
OS Version: 19045.3155
IntPtr Length: 8
x64: True

Python Path: C:\Python311\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 07/05/2023 04:17:03
Exception:
Google Search Plus Exception: 
Websites: https://github.com/jjw24/Wox.Plugin.GoogleSearch
Author: mikemorain
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: One or more errors occurred. (An attempt was made to access a socket in a way forbidden by its access permissions. (www.google.com:443))
 ---> System.AggregateException: One or more errors occurred. (An attempt was made to access a socket in a way forbidden by its access permissions. (www.google.com:443))
 ---> System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (www.google.com:443)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Wox.Plugin.GoogleSearch.GoogleSearch.Search(String query, Int32 limit) in D:\a\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\GoogleSearch.cs:line 30
   at Wox.Plugin.GoogleSearch.Main.Query(Query query) in D:\a\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\Main.cs:line 23
   at Flow.Launcher.Plugin.IPlugin.<>c__DisplayClass3_0.<Flow.Launcher.Plugin.IAsyncPlugin.QueryAsync>b__0() in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 836
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 837
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment] 2024-12-28 23:59
A fix has been added to get the plugin working again, not sure if this has solved your problem also, please test it out and let me know. Will close this issue in the meantime and reopen if problem persists.

**Closed by jjw24** 2024-12-28 23:59 UTC
