### ISSUE TITLE
Search results not showing up & removal from the Plugin Store

### ISSUE THREAD

**Issue by fourteen-1** [jjw24/Wox.Plugin.GoogleSearch#5] opened 2022-09-04 10:32 UTC
I just installed this plugin but the upon typing in something, no search results show up. 

How to fix this?

**Comment by jjw24** [comment] 2022-09-04 10:39
Hi, have you set it up in the Runner's settings? If so can you show me your config.

**Comment by jjw24** [comment] 2022-09-04 10:41
Hi, did you use the hotkey 'gs'?

**Comment by fourteen-1** [comment] 2022-09-06 15:56
It didn't work at first, but now it randomly started working. Its very slow to load the results, however (it takes at least 6-8 seconds to load). Is that a fixable issue?

**Comment by jjw24** [comment] 2022-09-19 10:39
Maybe but not sure without taking a proper look.

**Comment by thomasTAT** [comment] 2022-10-08 19:19
I have the same situation.

**Comment by jjw24** [comment] 2022-10-09 02:42
Hmm the only thing I can think of is internet connection. Could you attach the log when this happens again please.

**Comment by jjw24** [comment] 2022-11-02 21:56
Hey how's it going, are you still having this issue?

**Comment by fourteen-1** [comment] 2022-11-03 12:01
> Hey how's it going, are you still having this issue?

Hi Jeremy, 

Unfortunately, yes. It takes 3-5 seconds for the search results to show up. It depends though, on the search term length. the longer the search the more time it takes to load results. Sometimes very specific terms render no search results whatsoever.

Maybe it takes time for the plugin to load data from google? I couldn't tell you.

I'm currently relying on the native google search feature that can be found in the pre-installed Web Searches plugin.

**Comment by thiendiahui** [comment] 2023-06-02 19:26
Hi,I installed the plugin but it doesn't show anything, can you help me out ?
![flow](https://github.com/jjw24/Wox.Plugin.GoogleSearch/assets/59134330/ace0da85-b563-43c4-8382-68794510dea7)

**Comment by deefrawley** [comment] 2023-06-03 02:19
I can confirm the same issue. No results, just the loading bar for about a second then nothing. No errors logged.

**Comment by deefrawley** [comment] 2023-06-03 02:19
I can confirm the same issue. No results, just the loading bar for about a second then nothing. No errors logged.

**Comment by jjw24** [comment] 2023-08-07 08:27
Able to repro this one. Had a quick look, Google's results page layout has changed, so the plugin is no longer retrieving the correct element to parse the results.

Will need to spend some time to look at how to parse the search results on the website again.

**Comment by jjw24** [comment] 2023-08-07 08:28
Until fixed I believe this is happening for everyone.

**Comment by jjw24** [comment] 2023-08-22 03:33
> Able to repro this one. Had a quick look, Google's results page layout has changed, so the plugin is no longer retrieving the correct element to parse the results.
> 
> Will need to spend some time to look at how to parse the search results on the website again.

This is where the fallout occurs. The parsing is not picking up the right elements anymore.
https://github.com/jjw24/Wox.Plugin.GoogleSearch/blob/d74c0ad8f6a84d72dacca2ea4a11c5255453f128/GoogleSearch.cs#L41-L49

**Comment by jjw24** [comment] 2023-08-22 03:35
Due to priorities I will not have time to look into this plugin, and will remove it from the Store.

Anyone else please feel free to give it a go, I am still available to merge if a fix is found.

**Comment by jjw24** [comment] 2024-12-29 00:00
A fix has been added to get the plugin working again, not sure if this has solved your problem also, please test it out and let me know. Will close this issue in the meantime and reopen if problem persists.

**Closed by jjw24** 2024-12-29 00:00 UTC
Labels: bug, help wanted
